sudo: false
language:
    android
jdk:
    - oraclejdk8
android:
    components:
        - platform-tools
        - build-tools-23.0.1
        - android-23
        - extra-android-m2repository
        - sys-img-armeabi-v7a-android-19
script:
    - ./build/run-tests.sh
