sudo: false
language:
    android
jdk:
    - oraclejdk8
android:
    components:
        - platform-tools
        - tools

        - build-tools-22.0.1
        - android-19

        - extra-android-support
        - extra-android-m2repository

        - sys-img-armeabi-v7a-android-19
script:
    - ./build/run-tests.sh
